algoritmo "semnome"
// Função :por dois numeros e achar o menor dos dois
// Autor :Chrystian e Glauciana
// Data : 27/11/2010
// Seção de Declarações 
var
num,num2: inteiro

inicio
      escreval("Informe o Primeiro Número")
      leia(num)
      escreval("Informe o Segundo Número")
      leia(num2)
      Se num < num2 entao
         escreva("Esse número é o menor: ",num)
         senao
         escreva("Esse número é o menor: ",num2)
      fimse

fimalgoritmo
